DELETE http://localhost:8080/events/1/register 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIxMzMzMzQxLCJ1c2VySWQiOjJ9.YffSJsf_dq1jnaNtN5d0SKEIWGeTHeThDpoHcOF024U