POST http://localhost:8080/events/
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjEzMjkzNTAsInVzZXJJZCI6MX0.yYwZUkn0uQ5hbm4L3qnfVtw4gz79L3ZMayjqmd7cX0g

{
   "name": "Test event 1",
   "description": "This is a test event!!!",
   "location": "Test location",
   "dateTime": "2025-01-01T15:30:00.000Z"
}