POST http://localhost:8080/events/
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjEzMzI1MTAsInVzZXJJZCI6MX0.K0rwBW5wp8yFebMljqigcpdQKunModnhNSZbH24hHl8

{
   "name": "Test event",
   "description": "This is a test event!!!",
   "location": "Test location",
   "dateTime": "2025-01-01T15:30:00.000Z"
}