DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjEzMjk5MDMsInVzZXJJZCI6MX0.joUxQ5mVulTvIIhp6B3Un3aJ5rAyec2r9eSsORgyqbY